### ISSUE TITLE
Differentiate private gists in lsgists command

### ISSUE THREAD

**Issue by cuducos** [cuducos/getgist#12]
For example:

```
  Gist               File           URL
-----------------  -------------  -------------------------
README.md           My Gist #2      https://gist.github.com/…
anothe_file.md      My Gist #2      https://gist.github.com/…
file.md 🔒          First Gist 🔒    https://gist.github.com/…
```

Maybe 🔒 is not a good idea because it makes it more difficult to use withe `grep` (user has to input the emoji in the command, e.g.: `lsgists cuducos | grep 🔒`).

**Comment by vmesel** [comment]
@cuducos I, particularly,  like having `[PRIVATE]` in front of the filename, so we are able to see it's privacy.
What do you think about?

**Comment by cuducos** [comment]
>  I, particularly, like having [PRIVATE] in front of the filename

Agreed : )
